### ISSUE TITLE
Feaure-flagging LED effects (pyo3)

### ISSUE THREAD

**Issue by tuxuser** [vtavernier/hyperion.rs#2]
Hey!

How do you think about feature-flagging the python-dependant component "effects"?
It certainly helps the build process on embedded platforms ;)

Here is an example branch, implementing the feature `effects`: https://github.com/tuxuser/hyperion.rs/tree/task/feature_flag/py3
(the branch additionally adds another build target)

Do you consider it useful? And if so, how shall we proceed?

cheers

**Comment by alixinne** [comment]
Hello!

I was thinking about adding such a feature flag (third-party dependencies are indeed a pain on embedded platforms). As you've noticed the effect feature does creep up everywhere so feature-gating it does get ugly quite fast.

Thanks for doing the initial work, I'll review it in more detail in the coming days and let you know how we could proceed!
